### ISSUE TITLE
Pressing twice on a date

### ISSUE THREAD

**Issue by Nathan961207** [Tuslareb/JBDatePicker#5] opened 2017-01-12 19:46 UTC
When i accidentally pressed twice on a date it jumped to the left edge of the screen? Might be a simulator only bug? It happens every time you would press on the selected date multiple times but it returns to normal when you select a new date

**Comment by Tuslareb** [comment] 2017-01-12 22:18
Thanks for pointing me to this. It was an Auto Layout bug, caused by trying to reuse a already deinitialized selectionView object. Fixed with release 1.0.4. 

Please let me now if you have any further issues.

**Closed** 2017-01-12 22:24 UTC
